services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/conf.d/default.conf.template
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    entrypoint: /bin/bash -c "envsubst '\$ACTIVE_POOL' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:8000"
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:8000"
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green